{application,shop,
             [{description,"An OTP application"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{shop_app,[]}},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[cart,cart_sup,catalog,history,shop,shop_app,shop_sup,
                        tcp_handler,user,user_shop_sup]},
              {licenses,["Apache-2.0"]},
              {links,[]}]}.
